//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentDetail
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FatherOccupation { get; set; }
        public string MotherOccupation { get; set; }
        public string FatherOfficeAddress { get; set; }
        public string MotherOfficeAddress { get; set; }
        public string FofficePhone1 { get; set; }
        public string MofficePhone1 { get; set; }
        public string FofficePhone2 { get; set; }
        public string MofficePhone2 { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public byte[] CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
