//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slogan { get; set; }
        public string Addres { get; set; }
        public string Phones { get; set; }
        public string WebAddress { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string EdZone { get; set; }
        public string dateFounded { get; set; }
        public byte[] Logo { get; set; }
        public byte[] Bannar { get; set; }
        public byte[] CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
