//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyHistory
    {
        public int Id { get; set; }
        public string term { get; set; }
        public string @class { get; set; }
        public string classTeacher { get; set; }
        public string status { get; set; }
        public string studyYear { get; set; }
        public string studySession { get; set; }
        public string studyHistoryKey { get; set; }
    }
}
